# Generated by Django 6.0.1 on 2026-07-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('EAU', 'Eau'), ('ELECTRICITE', 'Électricité'), ('ENTRETIEN', 'Entretien'), ('INTERNET', 'Internet'), ('SALAIRE', 'Salaire'), ('TRANSPORT', 'Transport'), ('APPROVISIONNEMENT', 'Approvisionnement'), ('AUTRE', 'Autre')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
