services:
  - type: web
    name: gestion-appartements
    env: python

    plan: free

    buildCommand: "./build.sh"

    startCommand: "gunicorn config.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2

      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true