# Generated by Django 6.0.1 on 2026-06-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_mois', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('nom_client', models.CharField(max_length=200)),
                ('date_reservation', models.DateField()),
                ('type_location', models.CharField(choices=[('jour', 'Par Jour'), ('mois', 'Par Mois')], max_length=10)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('duree', models.IntegerField(default=0)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appartements.appartement')),
            ],
        ),
    ]
