# Generated by Django 6.0.1 on 2026-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='autres_frais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
