# Generated by Django 6.0.1 on 2026-06-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0002_reservation_autres_frais'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_location',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
